name: Test Environment Variables (Publish)

# on: [push, pull_request]
on:
  push:
    branches:
      - 'master'
      - '0*'
      - '1*'
      - '2*'
      - '3*'
      - '4*'
      - '5*'
      - '6*'
      - '7*'
      - '8*'
      - '9*'

jobs:
  environment_variables:
    name: Display Environment Variables
    runs-on: ubuntu-latest
    steps:
    - name: Build Environment Variables Text File
      run: |
        echo "CI = ${CI}" > env.txt
        echo "HOME = ${HOME}" >> env.txt
        echo "GITHUB_WORKFLOW = ${GITHUB_WORKFLOW}" >> env.txt
        echo "GITHUB_RUN_ID = ${GITHUB_RUN_ID}" >> env.txt
        echo "GITHUB_RUN_NUMBER = ${GITHUB_RUN_NUMBER}" >> env.txt
        echo "GITHUB_ACTION = ${GITHUB_ACTION}" >> env.txt
        echo "GITHUB_ACTIONS = ${GITHUB_ACTIONS}" >> env.txt
        echo "GITHUB_ACTOR = ${GITHUB_ACTOR}" >> env.txt
        echo "GITHUB_REPOSITORY = ${GITHUB_REPOSITORY}" >> env.txt
        echo "GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME}" >> env.txt
        echo "GITHUB_EVENT_PATH = ${GITHUB_EVENT_PATH}" >> env.txt
        echo "GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}" >> env.txt
        echo "GITHUB_SHA = ${GITHUB_SHA}" >> env.txt
        echo "GITHUB_REF = ${GITHUB_REF}" >> env.txt
        echo "GITHUB_HEAD_REF = ${GITHUB_HEAD_REF}" >> env.txt
        echo "GITHUB_BASE_REF = ${GITHUB_BASE_REF}" >> env.txt
        echo "GITHUB_SERVER_URL = ${GITHUB_SERVER_URL}" >> env.txt
        echo "GITHUB_API_URL = ${GITHUB_API_URL}" >> env.txt
        echo "GITHUB_GRAPHQL_URL = ${GITHUB_GRAPHQL_URL}" >> env.txt
    - name: Display Environment Variables Text File
      run: |
        cat env.txt
